### ISSUE TITLE
Can't inspect variables with dlv+rr

### ISSUE THREAD

**Issue by aarzilli** [HannoverGophers/talks#13]
This is not true, the likely reason that you couldn't inspect variables is that you probably didn't disable optimizations while compiling.

**Comment by tealeg** [comment]
@aarzilli great!  This document is archived at this point, but any tips are gratefully received.

**Comment by voigt** [comment]
You are probably referring to this:
https://github.com/HannoverGophers/talks/blob/master/meetup-2018-07-05/01_debugging-go/debugging.org#uing-rr-with-delve-3

This was part of a talk @tealeg gave on a meetup in july. Feel free to file a "edit:"-PR :)

@aarzilli thanks a lot for your input!!
